service: lighthouse-flows-generator

frameworkVersion: '3'

provider:
  name: aws
  region: ${env:MY_AWS_REGION}
  environment:
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
  ecr:
    images:
      lighthouse:
        path: .
        file: Dockerfile

functions:
  runLighthouse:
    image:
      name: lighthouse
    memorySize: 2048
    timeout: 180

package:
  individually: true
  exclude:
    - src/**
    - tsconfig.json
    - README.md
    - 計画書
    - .gitignore
    - .npmignore
    - bin
