service: lighthouse-flows-generator

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:MY_AWS_REGION}
  environment:
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}

functions:
  runLighthouse:
    name: ${env:LIGHTHOUSE_FUNCTION_NAME}
    handler: dist/commands/generate.handler
    memorySize: 1024
    timeout: 120

package:
  individually: true
  exclude:
    - src/**
    - tsconfig.json
    - README.md
    - 計画書
    - .gitignore
    - .npmignore
    - bin
